name: CI

on:
  push:
    branches: 
       - main
       - feature/*
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name : Copy secret
        env:
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
        
      - name : Grant execute permission for gradlew
        run : chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Run Tests
        env:
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
        run: ./gradlew test

